- README.md
- avaje-jex/src/main/java/io/avaje/jex/DJex.java
- avaje-jex/src/main/java/io/avaje/jex/Jex.java
- avaje-jex/src/test/java/io/avaje/jex/jdk/ExceptionManagerTest.java
> Remove duplicate exception method

- avaje-jex/src/main/java/io/avaje/jex/DefaultRouting.java
- avaje-jex/src/main/java/io/avaje/jex/Routing.java
- avaje-jex/src/test/java/io/avaje/jex/jdk/NestedRoutesTest.java
> Add OPTIONS

- avaje-jex/src/main/java/io/avaje/jex/Context.java
- avaje-jex/src/main/java/io/avaje/jex/jdk/JdkContext.java
Adds a method to get the body as an `InputStream`
> Add `bodyAsInputStream`

- avaje-jex/src/main/java/io/avaje/jex/DefaultRouting.java
- avaje-jex/src/main/java/io/avaje/jex/Routing.java
- avaje-jex/src/test/java/io/avaje/jex/DefaultErrorHandlingTest.java
- avaje-jex/src/test/java/io/avaje/jex/jdk/ExceptionManagerTest.java
> Rename Exception Method

- avaje-jex/src/main/java/io/avaje/jex/BootJexState.java
- avaje-jex/src/main/java/io/avaje/jex/Context.java
- avaje-jex/src/main/java/io/avaje/jex/Jex.java
- avaje-jex/src/main/java/io/avaje/jex/core/HealthPlugin.java
- avaje-jex/src/main/java/io/avaje/jex/jdk/JdkContext.java
- avaje-jex/src/main/java/io/avaje/jex/spi/JexPlugin.java
- adds header methods for list
- move `JexPlugin` into SPI package
> Add some header methods

- avaje-jex/src/main/java/io/avaje/jex/DJex.java
- avaje-jex/src/main/java/io/avaje/jex/DJexConfig.java
- avaje-jex/src/main/java/io/avaje/jex/ExceptionHandler.java
- avaje-jex/src/main/java/io/avaje/jex/Routing.java
- avaje-jex/src/main/java/io/avaje/jex/core/ExceptionManager.java
- avaje-jex/src/test/java/io/avaje/jex/DefaultErrorHandlingTest.java
- avaje-jex/src/test/java/io/avaje/jex/jdk/ExceptionManagerTest.java
Now all exceptions are properly handled
- catch and retry 
- re-order exception handler parameters
> Handle Exception Handlers Throwing Exceptions

- avaje-jex/src/main/java/io/avaje/jex/http/HttpResponseException.java
> Tidy HttpResponseException

- avaje-jex/src/main/java/io/avaje/jex/DefaultRouting.java
- avaje-jex/src/main/java/io/avaje/jex/Routing.java
- avaje-jex/src/test/java/io/avaje/jex/core/NestedRoutesTest.java
Makes it a little more intuitive I think
> change group to be a consumer

- README.md
- avaje-jex-static-content/src/main/java/io/avaje/jex/staticcontent/StaticResourceHandlerBuilder.java
- avaje-jex/src/main/java/io/avaje/jex/Jex.java
- avaje-jex/src/main/java/io/avaje/jex/Routing.java
I mean the consumer is nice and all, but the google java format makes it look pretty peculiar.
> Basic routing methods on `Jex`

- avaje-jex/src/main/java/io/avaje/jex/DefaultRouting.java
- avaje-jex/src/main/java/io/avaje/jex/Jex.java
- avaje-jex/src/main/java/io/avaje/jex/Routing.java
- avaje-jex/src/test/java/io/avaje/jex/core/NestedRoutesTest.java
It's a little more descriptive
> Rename `path` to `group`

- avaje-jex/src/main/java/io/avaje/jex/spi/JsonService.java
it honestly feels kind of niche
> Make `jsonWriteStream` a default method

- avaje-jex/src/main/java/io/avaje/jex/Context.java
- avaje-jex/src/main/java/io/avaje/jex/Jex.java
- avaje-jex/src/main/java/io/avaje/jex/core/JdkContext.java
- avaje-jex/src/main/java/io/avaje/jex/core/SpiServiceManager.java
- avaje-jex/src/main/java/io/avaje/jex/core/json/JacksonJsonService.java
- avaje-jex/src/main/java/io/avaje/jex/core/json/JsonbJsonService.java
- avaje-jex/src/main/java/io/avaje/jex/spi/JexPlugin.java
- avaje-jex/src/main/java/io/avaje/jex/spi/JsonService.java
- avaje-jex/src/main/java/io/avaje/jex/spi/TemplateRender.java
- avaje-jex/src/test/java/io/avaje/jex/core/JsonTest.java
- rename jsonService methods
- use java.lang.reflect.Type for deserialization
> Support generics in json

- avaje-jex/src/main/java/io/avaje/jex/BootJexState.java
- avaje-jex/src/main/java/io/avaje/jex/JexConfig.java
we can now configure the host/context path with avaje config
> Add more avaje config options

- pom.xml
Now will auto-run the ebean maven plugin if `META-INF/ebean-generated-info.mf` is detected
> Fix Jex version and autorun `Ebean`

- avaje-jex/src/main/java/io/avaje/jex/DJex.java
- avaje-jex/src/main/java/io/avaje/jex/DJexConfig.java
- avaje-jex/src/main/java/io/avaje/jex/Jex.java
- avaje-jex/src/main/java/io/avaje/jex/core/BootstrapServer.java
- avaje-jex/src/main/java/io/avaje/jex/routes/RoutesBuilder.java
- avaje-jex/src/test/java/io/avaje/jex/CtxPathTest.java
Currently setting the context path doesn't actually change any of the routes
> Fix `contextPath` having no effect on routes

- avaje-jex/src/main/java/io/avaje/jex/compression/CompressedOutputStream.java
- avaje-jex/src/main/java/io/avaje/jex/compression/CompressionConfig.java
- avaje-jex/src/test/java/io/avaje/jex/compression/CompressionTest.java
Adds support for specifying a custom compressor.
> Support Custom Compressors

- avaje-jex/src/main/java/io/avaje/jex/Context.java
- avaje-jex/src/main/java/io/avaje/jex/core/JdkContext.java
> Sort Context members

- avaje-jex/src/main/java/io/avaje/jex/DJexConfig.java
- avaje-jex/src/main/java/io/avaje/jex/JexConfig.java
> Increase default max buffer size

- avaje-jex/src/main/java/io/avaje/jex/DJexConfig.java
- avaje-jex/src/main/java/io/avaje/jex/JexConfig.java
- avaje-jex/src/main/java/io/avaje/jex/core/BootstrapServer.java
- avaje-jex/src/main/java/io/avaje/jex/core/JdkContext.java
- avaje-jex/src/main/java/io/avaje/jex/core/ServiceManager.java
- avaje-jex/src/main/java/io/avaje/jex/http/Context.java
- avaje-jex/src/test/java/io/avaje/jex/core/ContextLengthTest.java
- avaje-jex/src/test/java/io/avaje/jex/core/FilterTest.java
- avaje-jex/src/test/java/io/avaje/jex/core/RedirectTest.java
- Fix issue where path methods did not properly return path parameters
- replace URL method with URI
- retrieve the context path from the HttpExchange Context
- also disable that spi config (why did I even add that?)
> Fix path methods

- README.md
- avaje-jex/src/main/java/io/avaje/jex/Jex.java
- avaje-jex/src/main/java/io/avaje/jex/Routing.java
- avaje-jex/src/main/java/io/avaje/jex/SseHandler.java
- avaje-jex/src/main/java/io/avaje/jex/core/JdkContext.java
- avaje-jex/src/main/java/io/avaje/jex/core/ServiceManager.java
- avaje-jex/src/main/java/io/avaje/jex/core/json/JacksonJsonService.java
- avaje-jex/src/main/java/io/avaje/jex/core/json/JsonbJsonService.java
- avaje-jex/src/main/java/io/avaje/jex/http/Context.java
- avaje-jex/src/main/java/io/avaje/jex/http/sse/Emitter.java
- avaje-jex/src/main/java/io/avaje/jex/http/sse/SseClient.java
- avaje-jex/src/main/java/io/avaje/jex/http/sse/SseClientImpl.java
- avaje-jex/src/main/java/io/avaje/jex/http/sse/SseHandler.java
- avaje-jex/src/main/java/io/avaje/jex/spi/JsonService.java
- avaje-jex/src/main/java/module-info.java
- avaje-jex/src/test/java/io/avaje/jex/http/sse/SseClientTest.java
- Adds SSE methods to jex
- add `toJsonString` method to `jsonService`
- adds an sse package with classes to handle sse requests
> Add SSE support

- avaje-jex-test/src/main/java/io/avaje/jex/test/TestPair.java
- avaje-jex/src/main/java/io/avaje/jex/core/Constants.java
- avaje-jex/src/test/java/io/avaje/jex/core/CookieServerTest.java
- avaje-jex/src/test/java/io/avaje/jex/core/FilterTest.java
- avaje-jex/src/test/java/io/avaje/jex/core/TestPair.java
due to https://bugs.openjdk.org/browse/JDK-8347167, it's more efficient this way
> Normalize header constants

- avaje-jex/src/main/java/io/avaje/jex/http/HttpStatus.java
- avaje-jex/src/main/java/io/avaje/jex/http/package-info.java
- avaje-jex/src/main/java/io/avaje/jex/http/sse/package-info.java
- examples/example-http-generation/pom.xml
- examples/example-jdk-jsonb/pom.xml
- examples/example-jdk/pom.xml
- examples/example-jetty/pom.xml
- examples/example-robaho/pom.xml
- examples/pom.xml
now shouldn't fail build on version bump
> fix example builds

- avaje-jex-static-content/src/main/java/io/avaje/jex/staticcontent/StaticContent.java
- avaje-jex-static-content/src/test/java/io/avaje/jex/staticcontent/CompressedStaticFileTest.java
- avaje-jex-static-content/src/test/java/io/avaje/jex/staticcontent/StaticFileTest.java
- avaje-jex/src/main/java/io/avaje/jex/core/JdkContext.java
> Rename static content builder methods

- avaje-jex-static-content/src/main/java/io/avaje/jex/staticcontent/StaticContent.java
- avaje-jex/src/main/java/io/avaje/jex/core/BootstrapServer.java
also remove the version number from the start message (doesn't work on jlinked applications)
> [static content] add default resourceLoader method

- pom.xml
with this eclipse can run the plugins automatically if they're added to the project
> add m2e lifecycle config

- avaje-jex/src/main/java/io/avaje/jex/core/RoutingHandler.java
jetty can return 0 instead of -1 for unsent headers
> Fix Jetty no response

- .github/workflows/build.yml
- .github/workflows/jdk-ea.yml
- .github/workflows/jetty.yml
- .github/workflows/robaho.yml
- avaje-jex/pom.xml
It fails at the moment for reasons that will be fixed later.
Relies on https://github.com/jetty/jetty.project/pull/12929
> Add jetty GHA workflows

- avaje-jex/src/main/java/io/avaje/jex/core/JdkContext.java
> Don't close incoming InputStream

- avaje-jex/src/main/java/io/avaje/jex/DJexConfig.java
131_072 is too low for any video of decent size
> Increase Default Range Chunk Size

- avaje-jex/src/main/java/io/avaje/jex/core/RangeWriter.java
- Stop setting accept range header twice
- use ternary for 206/200 status
> Tidy Range writer

- avaje-jex/src/main/java/io/avaje/jex/http/sse/SseHandler.java
Now will not throw an exception for multivalue accept headers
> [SSE] Relax SSE Accept Header Validation

- avaje-jex-ssl/src/main/java/io/avaje/jex/ssl/DSslConfig.java
- avaje-jex-ssl/src/main/java/io/avaje/jex/ssl/KeyStoreUtil.java
- avaje-jex-ssl/src/main/java/io/avaje/jex/ssl/SSLContextFactory.java
- avaje-jex-ssl/src/main/java/io/avaje/jex/ssl/SslConfig.java
- avaje-jex-ssl/src/test/java/io/avaje/jex/ssl/PemLoadingTests.java
- avaje-jex/pom.xml
- pom.xml
Add config method for resource loader
> add resource loader config
